name: Deploy to EKS

on:
  push:
    branches: [ main, dev, staging ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::074002960123:role/rashiyamani-collab-azure-gittesting3-oidc-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 074002960123.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t 074002960123.dkr.ecr.ap-south-1.amazonaws.com/myapp:$IMAGE_TAG .
          docker push 074002960123.dkr.ecr.ap-south-1.amazonaws.com/myapp:$IMAGE_TAG

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name demo-eks-dev --region ap-south-1

      - name: Deploy to EKS
        run: |
             kubectl get pods -A
             kubectl apply -f k8s/app-deployment.yaml --validate=false
             kubectl apply -f k8s/app-service.yaml --validate=false
