name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::074002960123:role/rashiyamani-collab-azure-gittesting3-oidc-role
          aws-region: ap-south-1
          
      - name: Test kubectl
        run: | 
          aws eks update-kubeconfig --region ap-south-1 --name demo-eks-dev
          kubectl config current-context
          aws sts get-caller-identity
          aws eks describe-cluster --name demo-eks-dev --region ap-south-1

